#include <avr/io.h>

#define _SET_PIN_OUTPUT(PORT, PIN) (DDR##PORT |= _BV(PIN))
#define SET_PIN_OUTPUT(PINSPEC)    _SET_PIN_OUTPUT(PINSPEC)

#define _SET_PIN_INPUT(PORT, PIN) (DDR##PORT &= ~_BV(PIN))
#define SET_PIN_INPUT(PINSPEC)    _SET_PIN_OUTPUT(PINSPEC)

#define _PIN_OUTPUT_HIGH(PINPORT, PIN) (PORT##PINPORT |= _BV(PIN))
#define PIN_OUTPUT_HIGH(PINSPEC)    _PIN_OUTPUT_HIGH(PINSPEC)

#define _PIN_OUTPUT_LOW(PINPORT, PIN) (PORT##PINPORT &= ~_BV(PIN))
#define PIN_OUTPUT_LOW(PINSPEC)    _PIN_OUTPUT_LOW(PINSPEC)

#define _PIN_OUTPUT_VALUE(PINPORT, PIN, VALUE) (PORT##PINPORT = (VALUE ? (PORT##PINPORT | _BV(PIN)) : (PORT##PINPORT & ~_BV(PIN))))
#define PIN_OUTPUT_VALUE(PINSPEC, VALUE)  _PIN_OUTPUT_VALUE(PINSPEC, VALUE)

#define _PIN_READ(PORT, PIN_NUM)       ((PIN##PORT & _BV(PIN_NUM)) >> PIN_NUM)
#define PIN_READ(PINSPEC)          _PIN_READ(PINSPEC)